"""Generate graphical EMG training analysis.

This module complements the training scripts with plots inspired by the
DESARROLLO folder: class balance, confusion matrices already generated by the
trainers, feature separability and RandomForest feature importance.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.common.labels import CLASS_COLORS, LABEL_ALIASES

RAW_CHANNELS = ["emg_ch1", "emg_ch2", "emg_ch3", "emg_ch4"]
FEATURES_PER_CHANNEL = ["mean", "std", "min", "max", "mav", "rms", "wl"]


def normalize_label(label: object) -> str | None:
    if not isinstance(label, str):
        return None
    return LABEL_ALIASES.get(label.strip().lower())


def feature_names() -> list[str]:
    names = []
    for channel in RAW_CHANNELS:
        for feature in FEATURES_PER_CHANNEL:
            names.append(f"{channel}_{feature}")
    return names


def load_dataset(input_dir: Path) -> pd.DataFrame:
    files = sorted(input_dir.rglob("*.csv"))
    if not files:
        raise RuntimeError(f"No se encontraron CSV en {input_dir}")

    frames = []
    for path in files:
        frame = pd.read_csv(path)
        missing = [column for column in RAW_CHANNELS + ["movement_label"] if column not in frame.columns]
        if missing:
            print(f"Saltando {path.name}: faltan columnas {missing}")
            continue

        frame = frame.copy()
        frame["source_file"] = path.name
        frame["target_label"] = frame["movement_label"].map(normalize_label)
        frame = frame.dropna(subset=["target_label"])
        for channel in RAW_CHANNELS:
            frame[channel] = pd.to_numeric(frame[channel], errors="coerce")
        frame = frame.dropna(subset=RAW_CHANNELS)
        if not frame.empty:
            frames.append(frame)

    if not frames:
        raise RuntimeError("No hay muestras utiles con etiquetas de movimiento.")
    return pd.concat(frames, ignore_index=True)


def segment_groups(dataset: pd.DataFrame):
    for source_file, file_frame in dataset.groupby("source_file", sort=False):
        file_frame = file_frame.reset_index(drop=True)
        change = file_frame["target_label"].ne(file_frame["target_label"].shift()).cumsum()
        for segment_id, segment in file_frame.groupby(change, sort=False):
            label = str(segment["target_label"].iloc[0])
            yield source_file, int(segment_id), label, segment


def extract_features(window: np.ndarray) -> np.ndarray:
    features = []
    for channel in range(window.shape[1]):
        values = window[:, channel].astype(np.float64)
        diff = np.diff(values)
        features.extend(
            [
                np.mean(values),
                np.std(values),
                np.min(values),
                np.max(values),
                np.mean(np.abs(values)),
                np.sqrt(np.mean(values**2)),
                np.sum(np.abs(diff)),
            ]
        )
    return np.array(features, dtype=np.float32)


def build_feature_windows(dataset: pd.DataFrame, window_size: int, stride: int) -> tuple[np.ndarray, np.ndarray]:
    x_rows = []
    y_rows = []
    for _source_file, _segment_id, label, segment in segment_groups(dataset):
        values = segment[RAW_CHANNELS].to_numpy(dtype=np.float32)
        if len(values) < window_size:
            continue
        for start in range(0, len(values) - window_size + 1, stride):
            window = values[start : start + window_size]
            x_rows.append(extract_features(window))
            y_rows.append(label)

    if not x_rows:
        raise RuntimeError("No se pudieron crear ventanas para el reporte.")
    return np.vstack(x_rows), np.array(y_rows)


def save_class_balance(labels_text: np.ndarray, output_path: Path) -> Counter:
    counts = Counter(str(label) for label in labels_text)
    labels = sorted(counts)
    values = [counts[label] for label in labels]
    colors = [CLASS_COLORS.get(label, "#64748b") for label in labels]

    figure, axis = plt.subplots(figsize=(10, 5))
    axis.bar(labels, values, color=colors)
    axis.set_title("Balance de ventanas por movimiento")
    axis.set_xlabel("Movimiento")
    axis.set_ylabel("Ventanas de entrenamiento")
    axis.tick_params(axis="x", labelrotation=35)
    axis.grid(axis="y", alpha=0.25)
    figure.tight_layout()
    figure.savefig(output_path, dpi=170)
    plt.close(figure)
    return counts


def save_pca_separability(x: np.ndarray, labels_text: np.ndarray, output_path: Path, max_points: int) -> None:
    if len(x) > max_points:
        rng = np.random.default_rng(42)
        indices = rng.choice(len(x), size=max_points, replace=False)
        x_plot = x[indices]
        y_plot = labels_text[indices]
    else:
        x_plot = x
        y_plot = labels_text

    scaled = StandardScaler().fit_transform(x_plot)
    points = PCA(n_components=2, random_state=42).fit_transform(scaled)
    labels = sorted(set(str(label) for label in y_plot))

    figure, axis = plt.subplots(figsize=(9, 7))
    for label in labels:
        mask = y_plot == label
        axis.scatter(
            points[mask, 0],
            points[mask, 1],
            s=14,
            alpha=0.65,
            label=label,
            color=CLASS_COLORS.get(label, None),
        )
    axis.set_title("Separacion de movimientos con PCA")
    axis.set_xlabel("Componente principal 1")
    axis.set_ylabel("Componente principal 2")
    axis.legend(loc="best", fontsize=8)
    axis.grid(alpha=0.25)
    figure.tight_layout()
    figure.savefig(output_path, dpi=170)
    plt.close(figure)


def save_signal_examples(dataset: pd.DataFrame, output_path: Path, max_samples: int) -> None:
    examples: dict[str, pd.DataFrame] = {}
    for _source_file, _segment_id, label, segment in segment_groups(dataset):
        if label not in examples:
            examples[label] = segment.head(max_samples)

    labels = sorted(examples)
    figure, axes = plt.subplots(len(labels), 1, figsize=(12, max(7, len(labels) * 1.55)), sharex=False)
    if len(labels) == 1:
        axes = [axes]

    colors = ["#2563eb", "#f97316", "#16a34a", "#dc2626"]
    for axis, label in zip(axes, labels):
        segment = examples[label]
        values = segment[RAW_CHANNELS].to_numpy(dtype=np.float32)
        offset = max(1500.0, float(np.nanstd(values)) * 5.0)
        x_values = np.arange(len(values))
        for channel_index, color in enumerate(colors):
            axis.plot(
                x_values,
                values[:, channel_index] + offset * channel_index,
                color=color,
                linewidth=0.8,
                label=f"CH{channel_index + 1}" if label == labels[0] else None,
            )
        axis.set_ylabel(label)
        axis.grid(alpha=0.25)

    axes[0].legend(loc="upper right", ncol=4)
    axes[-1].set_xlabel("Muestras")
    figure.suptitle("Ejemplos de senal por movimiento", y=0.995)
    figure.tight_layout()
    figure.savefig(output_path, dpi=170)
    plt.close(figure)


def save_feature_importance(models_dir: Path, output_path: Path) -> bool:
    model_path = models_dir / "emg_sklearn_baseline.joblib"
    if not model_path.exists():
        return False

    model = joblib.load(model_path)
    importances = getattr(model, "feature_importances_", None)
    if importances is None:
        return False

    names = np.array(feature_names())
    order = np.argsort(importances)[-20:]

    figure, axis = plt.subplots(figsize=(9, 7))
    axis.barh(names[order], importances[order], color="#2563eb")
    axis.set_title("Importancia de caracteristicas - RandomForest")
    axis.set_xlabel("Importancia relativa")
    axis.grid(axis="x", alpha=0.25)
    figure.tight_layout()
    figure.savefig(output_path, dpi=170)
    plt.close(figure)
    return True


def write_markdown_report(
    metrics_dir: Path,
    figures_dir: Path,
    counts: Counter,
    total_windows: int,
    source_files: int,
    generated: list[Path],
) -> Path:
    report_path = metrics_dir / "reporte_grafico_entrenamiento.md"
    lines = [
        "# Reporte grafico de diferenciacion EMG",
        "",
        "Este reporte resume si las senales de los movimientos se diferencian entre si.",
        "",
        f"- Archivos CSV analizados: {source_files}",
        f"- Ventanas creadas: {total_windows}",
        "",
        "## Ventanas por clase",
        "",
    ]
    for label, count in sorted(counts.items()):
        lines.append(f"- {label}: {count}")

    lines.extend(["", "## Figuras generadas", ""])
    for path in generated:
        lines.append(f"- {path.name}")

    known_figures = [
        figures_dir / "sklearn_baseline_confusion_matrix.png",
        figures_dir / "confusion_matrix.png",
        figures_dir / "tiny_mlp_confusion_matrix.png",
        figures_dir / "training_history.png",
        figures_dir / "tiny_mlp_training_history.png",
    ]
    existing = [path for path in known_figures if path.exists()]
    if existing:
        lines.extend(["", "## Figuras de entrenamiento existentes", ""])
        for path in existing:
            lines.append(f"- {path.name}")

    lines.extend(
        [
            "",
            "## Como interpretarlo",
            "",
            "- La matriz de confusion muestra en la diagonal los aciertos por movimiento.",
            "- El grafico PCA muestra si las ventanas forman grupos separables.",
            "- La importancia de caracteristicas indica que canales y medidas aportan mas al modelo base.",
            "- Si dos clases aparecen mezcladas, se necesitan mas sesiones o mejorar la ubicacion de electrodos.",
            "",
        ]
    )
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def parse_args():
    parser = argparse.ArgumentParser(description="Generar reporte grafico de entrenamiento EMG.")
    parser.add_argument("--input-dir", type=Path, default=PROJECT_ROOT / "data" / "raw")
    parser.add_argument("--models-dir", type=Path, default=PROJECT_ROOT / "models")
    parser.add_argument("--figures-dir", type=Path, default=PROJECT_ROOT / "results" / "figures")
    parser.add_argument("--metrics-dir", type=Path, default=PROJECT_ROOT / "results" / "metrics")
    parser.add_argument("--window-size", type=int, default=200)
    parser.add_argument("--stride", type=int, default=50)
    parser.add_argument("--max-pca-points", type=int, default=5000)
    parser.add_argument("--max-signal-samples", type=int, default=450)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.figures_dir.mkdir(parents=True, exist_ok=True)
    args.metrics_dir.mkdir(parents=True, exist_ok=True)

    dataset = load_dataset(args.input_dir)
    x, labels_text = build_feature_windows(dataset, args.window_size, args.stride)

    generated: list[Path] = []
    balance_path = args.figures_dir / "analisis_01_balance_clases.png"
    pca_path = args.figures_dir / "analisis_02_pca_separabilidad.png"
    signals_path = args.figures_dir / "analisis_03_ejemplos_senales.png"
    importance_path = args.figures_dir / "analisis_04_importancia_caracteristicas.png"

    counts = save_class_balance(labels_text, balance_path)
    generated.append(balance_path)
    save_pca_separability(x, labels_text, pca_path, args.max_pca_points)
    generated.append(pca_path)
    save_signal_examples(dataset, signals_path, args.max_signal_samples)
    generated.append(signals_path)
    if save_feature_importance(args.models_dir, importance_path):
        generated.append(importance_path)

    report_path = write_markdown_report(
        args.metrics_dir,
        args.figures_dir,
        counts,
        total_windows=len(x),
        source_files=dataset["source_file"].nunique(),
        generated=generated,
    )

    print("Reporte grafico generado.")
    print(f"CSV analizados: {dataset['source_file'].nunique()}")
    print(f"Ventanas: {len(x)}")
    print(f"Figuras: {args.figures_dir}")
    print(f"Resumen: {report_path}")


if __name__ == "__main__":
    main()
